In [1]:
import torch

In [2]:
torch.__version__

'2.5.1'

In [3]:
torch.cuda.is_available()

False

In [4]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [6]:
scalar.item()

7

In [7]:
scalar.ndim

0

In [8]:
vector = torch.tensor([1, 2, 3, 4, 5])
print(vector)
print(vector.ndim)

tensor([1, 2, 3, 4, 5])
1


In [10]:
vector.shape

torch.Size([5])

In [12]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix.ndim)
print(matrix.shape)
print(matrix)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [13]:
tensor = torch.tensor(
    [
        [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
        [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
        [[19, 20, 21], [22, 23, 24], [25, 26, 27]],
    ]
)
print(tensor.ndim)
print(tensor.shape)
print(tensor)

3
torch.Size([3, 3, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])


In [14]:
print("XPU available:", torch.xpu.is_available())

XPU available: False
