### PyTorch Tensors


In [3]:
import torch
import numpy as np

### Initializing tensors

In [2]:
# directly from data
data = [[2,3],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[2, 3],
        [3, 4]])

In [4]:
# from numpy ararys
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[2, 3],
        [3, 4]], dtype=torch.int32)

In [8]:
# from other tensors

x_ones = torch.ones_like(x_data)
x_ones

x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.8515, 0.1855],
        [0.0680, 0.4365]])

In [11]:

# with random or constant values

shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Rand Tensor \n {rand_tensor} \n')
print(f'Ones Tensor \n {ones_tensor} \n')
print(f'Zeroes Tensor \n {zeros_tensor} \n')

Rand Tensor 
 tensor([[0.4309, 0.7128, 0.8204],
        [0.1954, 0.4015, 0.0619]]) 

Ones Tensor 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeroes Tensor 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Tensor Attributes